
# /Test 
GET http://localhost:3001/test

# Get Books
###
GET http://localhost:3001/books

# /post Book
###
POST http://localhost:3001/books
Content-Type: application/json

{
  "title": "Book1",
  "description": "Hi harry",
  "status": "wizard",
  "email": "Cow@farm.com"
}

# PUT BOOKS
###
PUT http://localhost:3001/books/617dbd7160e72f300bc8f655
Content-Type: application/json

{
  "title": "Harry Potter",
  "description": "Hi harry",
  "status": "wizard",
  "email": "harrworld@hogwarts.com"
}



# CLEAR
###
DELETE http://localhost:3001/clear








# HEROKU /test
###
GET https://paperlouse-can-of-books.herokuapp.com/test

#HEROKU /books
###
GET https://paperlouse-can-of-books.herokuapp.com/books 

# HEROKU /addseeds
###
GET https://paperlouse-can-of-books.herokuapp.com/addseeds
