
# /Test Route
GET http://localhost:3001/test

# /books
###
GET http://localhost:3001/books

# /post
###

POST http://localhost:3001/books
Content-Type: application/json

{
  "title": "TEST3",
  "description": "Hi harry",
  "status": "wizard",
  "email": "Cow@farm.com"
}

# PUT BOOKS
###
PUT http://localhost:3001/books/617dbd7160e72f300bc8f655
Content-Type: application/json

{
  "title": "Harry Potter",
  "description": "Hi harry",
  "status": "wizard",
  "email": "harrworld@hogwarts.com"
}












# HEROKU /test
###
GET https://paperlouse-can-of-books.herokuapp.com/test

#HEROKU /books
###
GET https://paperlouse-can-of-books.herokuapp.com/books 

# HEROKU /addseeds
###
GET https://paperlouse-can-of-books.herokuapp.com/addseeds
